base_url = "https://zola-mikoto.netlify.com/"
title = "mikoto theme"
description = ""
compile_sass = true
highlight_code = true
highlight_theme = "one-dark"
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
    {name = "series", rss = true},
]



theme = "mikoto"
extra_syntaxes = ["syntaxes"]



[extra]
author = "Aster"
mikoto_title = "Mikoto"

github_link = "https://github.com/GalAster/zola-theme-mikoto"

# comment `enable` to close the plugin

aplayer_enable = true
aplayer_background = true
aplayer_background_server = "netease"
aplayer_background_type = "album"
aplayer_background_id = "82260016"

live2d_enable = true

mathjax_enable = true
katex_enalbe = false

