base_url = "https://zola-even.netlify.com"

compile_sass = true
title = "mikoto theme"
description = ""
highlight_code = true
highlight_theme = "monokai"
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
    {name = "series", rss = true},
]
theme = "mikoto"

[extra]
author = "Aster"
mikoto_title = "Mikoto"

# comment `enable` to close the plugin

aplayer_enable = true
# aplayer_cdn_js = ""
# aplayer_cdn_css = ""
# aplayer_cdn_meting = ""
aplayer_background = true
aplayer_background_server = "netease"
aplayer_background_type = "album"
aplayer_background_id = "82260016"

live2d_enbale = true

mathjax_enable = true
# mathjax_cdn = ""
katex_enalbe = false
# katex_cdn = ""
