base_url = "https://zola-even.netlify.com"

compile_sass = true
title = "mikoto theme"
description = ""
highlight_code = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "Aster"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/series", name = "Series"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "Mikoto"

[extra.aplayer]
enable = true
cdn_js = ""
cdn_css = ""
cdn_meting = ""

[extra.aplayer.background]
enable = true
server = "netease"
type = "album"
id = "82260016"

[extra.live2d]
enbale = true


