name = "mikoto"
description = "A robust, elegant dark theme"
license = "MIT"
homepage = ""
min_version = "0.8.0"
demo = ""

[extra]
mikoto_title = "Mikoto"
mikoto_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/series", name = "Series"},
    {url = "$BASE_URL/about", name = "About"},
]

[author]
name = "Aster"
homepage = ""

[original]
name = "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"
repo = "https://github.com/getzola/even"
